apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: programmerhumor
  labels:
    app: programmerhumor
spec:
  selector:
    matchLabels:
      app: programmerhumor
  template:
    metadata:
      labels:
        app: programmerhumor
        name: programmerhumor
    spec:
      containers:
      - image: cooljacob204/programmerhumor:latest
        name: programmerhumor
        ports:
        - containerPort: 5000
          name: programmerhumor
---
apiVersion: v1
kind: Service
metadata:
  name: programmerhumor
spec:
  type: NodePort
  selector:
    app: programmerhumor
  ports:
  - port: 5000
    targetPort: 5000