apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lfp2-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: lfp2-ip
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
  labels:
    app: lfp2
spec:
  tls:
  - secretName: guest-portal-lfp2-gg-tls
    hosts:
    - guest-portal.lfp2.gg
  - secretName: videogame-tracker-lfp2-gg-tls
    hosts:
    - videogame-tracker.lfp2.gg
  - secretName: jenkins-lfp2-gg
    hosts:
    - jenkins.lfp2.gg
  - secretName: airflow-lfp2-gg
    hosts:
    - airflow.lfp2.gg
  - secretName: flower-lfp2-gg
    hosts:
    - flower.lfp2.gg
  
  rules:
  - host: guest-portal.lfp2.gg
    http:
      paths:
      - path: /*
        backend:
          serviceName: videogame-tracker
          servicePort: 80
  - host: videogame-tracker.lfp2.gg
    http:
      paths:
      - path: /*
        backend:
          serviceName: videogame-tracker
          servicePort: 80
  - host: jenkins.lfp2.gg
    http:
      paths:
      - path: /*
        backend:
          serviceName: jenkins
          servicePort: 80
  - host: airflow.lfp2.gg
    http:
      paths:
      - path: /*
        backend:
          serviceName: airflow-web
          servicePort: 8080
  - host: flower.lfp2.gg
    http:
      paths:
      - path: /*
        backend:
          serviceName: airflow-flower
          servicePort: 5555