apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins # replace this with the username you want to use
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jenkins # replace this with the username you want to use
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins # replace this with the username you want to use
  namespace: default