# webserver
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: airflow-web
  labels:
    app: airflow-web
spec:
  selector:
    matchLabels:
      app: airflow-web
  template:
    metadata:
      labels:
        app: airflow-web
        name: airflow
    spec:
      containers:
      - image: cooljacob204/airflow
        name: airflow-web
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-conn
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-backend
        - name: AIRFLOW__WEBSERVER__AUTHENTICATE
          value: "True"
        - name: AIRFLOW__WEBSERVER__AUTH_BACKEND
          value: "airflow.contrib.auth.backends.password_auth"
        command: ["airflow"]
        args: ["webserver"]
        ports:
        - containerPort: 8080
          name: webserver
      hostname: webserver
      subdomain: airflow
---
# scheduler
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: airflow-sched
  labels:
    app: airflow-sched
spec:
  selector:
    matchLabels:
      app: airflow-sched
  template:
    metadata:
      labels:
        app: airflow-sched
        name: airflow
    spec:
      containers:
      - image: cooljacob204/airflow
        name: airflow-sched
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-conn
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-backend
        command: ["airflow"]
        args: ["scheduler"]
      hostname: scheduler
      subdomain: airflow
---
# workers
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: airflow-worker
  labels:
    app: airflow-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
        name: airflow
    spec:
      containers:
      - image: cooljacob204/airflow
        name: airflow-worker
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-conn
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-backend
        command: ["airflow"]
        args: ["worker"]
      subdomain: airflow
---
# redis for celery
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: airflow-redis
  labels:
    app: airflow-redis
spec:
  selector:
    matchLabels:
      app: airflow-redis
  template:
    metadata:
      labels:
        app: airflow-redis
        name: airflow
    spec:
      containers:
      - image: redis:3.2.7
        name: airflow-redis
        ports:
        - containerPort: 6379
          name: redis
      hostname: redis
      subdomain: airflow
---
# flower
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: airflow-flower
  labels:
    app: airflow-flower
spec:
  selector:
    matchLabels:
      app: airflow-flower
  template:
    metadata:
      labels:
        app: airflow-flower
        name: airflow
    spec:
      containers:
      - image: cooljacob204/airflow
        name: airflow-flower
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-conn
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-backend
        command: ["airflow"]
        args: ["flower"]
        ports:
        - containerPort: 5555
          name: redis
      subdomain: airflow