apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  selector:
    name: airflow
  clusterIP: None
  ports:
  - name: foo
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-web
spec:
  type: NodePort
  selector:
    app: airflow-web
  ports:
  - name: ui
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-flower
spec:
  type: NodePort
  selector:
    app: airflow-flower
  ports:
  - name: ui
    protocol: TCP
    port: 5555
    targetPort: 5555